### ISSUE TITLE
Styling enhancements proposal

### ISSUE THREAD

**Issue by maringerov** [meteor/tutorial-viewer#1]
Hi @stubailo, would you like some help with some minor adjustments to the styling of the app? If so, I would love to contribute :) 

PS: Great project!

**Comment by stubailo** [comment]
Sounds great! Keep in mind though that this app is mostly for testing/development of the tutorial and won't be used for the production version on Meteor.com, so improving its appearance might not be the most useful investment of efforts.

If you would like to help with maintainability of the tutorials, I have a lot of other tasks that I can make available.

**Comment by maringerov** [comment]
Sure, I would love to help. I am still getting into Meteor  and working on the code samples might be a bit too much for me, but I guess there are other ways I can contribute to. Thanks!

**Comment by abernix** [comment]
Closing as this is pretty stale, but if you're interested in contributing still, let us know! :)  https://github.com/meteor/meteor/blob/devel/Contributing.md

Thanks! :)
