### ISSUE TITLE
Error: Multiple files in patch.

### ISSUE THREAD

**Issue by ShavonnahTiera** [meteor/tutorial-viewer#4]
I'm getting a fun error message that's preventing a few of my templates from rendering:

`Error: Multiple files in patch. Must specify filename which is one of: .meteor/packages, .meteor/versions`

The patch file I have has been autogenerated. Thoughts on a fix?

**Comment by stubailo** [comment]
It looks like the commit contains changes to multiple files at once. You need to specify which file you are interested in showing a diff for using the relevant option: https://github.com/meteor/tutorial-tools/blob/0053610cdeccadc09b3e722ce4b93d35756ce419/tutorial-diff-box/diff-box.jsx#L20

However, in this case, I would suggest that showing a diff for a commit where you only change the packages and versions file wouldn't be useful. in this case, I think just saying "Run `meteor add package:name`" is good enough.

So if you have some commits where you are adding or removing packages, I would suggest just not rendering a diff box for those.
